# Profil DEV - surcharge application.properties
# Lancer avec : -Dspring.profiles.active=dev

spring.datasource.url=jdbc:mysql://localhost:3306/java_des_heros_dev?useSSL=false&serverTimezone=Europe/Paris&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
